### PR TITLE
Added keep-only-s3 option

### PR DESCRIPTION
**Pull request by alexw23**
My backup folder was filling up - ended up being 8GB. Realised that s3 upload option isn't actually removing the dumps once it's been sent to s3. I've added the ability to use --unlink-after-s3 (happy for you to rename as you like). This will unlink the file if the option is set.

### CODE REVIEW

**Comment by schickling** [comment]
Thanks @alexw23 for your pull request. Could you please rename the option to `--keep-only-s3` (what do you think about that name?) and please provide a test case for that feature.

**Comment by alexw23** [comment]
Done :shipit:

**Comment by schickling** [comment]
Perfect thanks @alexw23 !

**Comment by lostincode** [comment]
@schickling Are you gonna tag a version for this?

**Comment by schickling** [comment]
Done :+1:

**Pull request merged**
