### PR TITLE
Add the possibility to directly tell where is mysql and mysqldump + adding color for the output in the command line

### PR DESCRIPTION
**Pull request by 100terres**
sorry for my English

### CODE REVIEW

**Comment by schickling** [comment]
Thanks @gabrielsanterre for your work!

Could you please make the tests green again? Then I'll review and merge! :+1:

**Comment by 100terres** [comment]
Okay okay ...

**Comment by 100terres** [comment]
haha

**Comment by schickling** [comment]
Thanks @gabrielsanterre :+1:

**Pull request merged**
