### PR TITLE
L5 patch v2 - updated unit tests

### PR DESCRIPTION
**Pull request by dealloc**

### CODE REVIEW

**Comment by schickling** [comment]
Hmm tests don't seem to run...

**Comment by nickurt** [comment]
Yeah, it's using the core of Laravel 4.1.x and not 5.0.*

**Comment by schickling** [comment]
@Jir0, if you could you fix the tests, I'd love to merge this.

**Comment by dealloc** [comment]
I've been trying but I don't even get the ones from the official repositories working...

**Pull request closed without merging**
