### PR TITLE
add port to mysqldump

### LINKED ISSUE #16: Support for mysql port
Is there any way to specify the mysql port? e.g. -P 3307 in the mysqldump command

### PR DESCRIPTION
**Pull request by lostincode**
Add port to mysqldump with default value fix #16

### CODE REVIEW

**Comment by schickling** [comment]
Thanks @lostincode but could you also adjust the tests please?

**Comment by lostincode** [comment]
Absolutely! I have them working already but I am unsure how to set a default for $config['port'] in the test with DatabaseBuilder.php. The test will fail 'ErrorException: Undefined index: port'. Any advice here?

``` php
    protected function buildMySQL(array $config)
    {
        $port = isset($config['port']) ? $config['port'] : '';
        $this->database = new Databases\MySQLDatabase(
            $this->console,
            $config['database'],
            $config['username'],
            $config['password'],
            $config['host'],
            $port
            );
    }
```

The above works but seems ugly.

**Comment by schickling** [comment]
I guess you need to specify the port here: https://github.com/schickling/laravel-backup/blob/master/tests/DatabaseBuilderTest.php

**Comment by lostincode** [comment]
I did that and it will still fail...

**Comment by schickling** [comment]
Thanks, I'll work on it!

**Pull request merged**
