### PR TITLE
Move dependencies to require-dev, as it only needed during development. Fixed travis-ci while I'm at it.

### PR DESCRIPTION
**Pull request by crynobone**
Signed-off-by: crynobone crynobone@gmail.com

Before composer.json changes.

``` bash
➜  laravel-backup git:master ✓ composer install --dry-run
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[4.1.x-dev, 4.0.x-dev].
    - Can only install one of: laravel/framework[v4.0.0, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.0-BETA2, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.0-BETA3, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.0-BETA4, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.1, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.2, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.3, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.4, 4.1.x-dev].
    - Can only install one of: laravel/framework[v4.0.5, 4.1.x-dev].
    - don't install illuminate/foundation 4.0.x-dev|don't install laravel/framework 4.1.x-dev
    - orchestra/testbench 2.1.x-dev requires laravel/framework 4.1.* -> satisfiable by laravel/framework[4.1.x-dev].
    - Installation request for orchestra/testbench 2.1.* -> satisfiable by orchestra/testbench[2.1.x-dev].
    - Installation request for illuminate/foundation 4.0.x -> satisfiable by illuminate/foundation[4.0.x-dev], laravel/framework[4.0.x-dev, v4.0.0, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.1, v4.0.2, v4.0.3, v4.0.4, v4.0.5].
```

After changes

``` bash
➜  laravel-backup git:master ✗ composer install --dry-run
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing mockery/mockery (dev-master 92fad36)

  - Installing symfony/translation (2.3.x-dev v2.3.1)

  - Installing psr/log (1.0.0)

  - Installing doctrine/lexer (dev-master bc0e1f0)

  - Installing doctrine/annotations (v1.1.1)

  - Installing doctrine/collections (dev-master 3db3ab8)

  - Installing doctrine/cache (dev-master 89493d2)

  - Installing doctrine/inflector (dev-master 8b4b3cc)

  - Installing doctrine/common (dev-master 2.4.0-RC4)

  - Installing symfony/routing (2.3.x-dev 3deda53)

  - Installing symfony/process (2.3.x-dev f12e585)

  - Installing symfony/debug (2.3.x-dev v2.3.1)

  - Installing symfony/http-foundation (2.3.x-dev 997715d)

  - Installing symfony/event-dispatcher (2.3.x-dev v2.3.1)

  - Installing symfony/http-kernel (2.3.x-dev 98c849c)

  - Installing symfony/finder (2.3.x-dev efe739e)

  - Installing symfony/dom-crawler (2.3.x-dev 761ea57)

  - Installing symfony/css-selector (2.3.x-dev e4f7310)

  - Installing symfony/console (2.3.x-dev 911cdac)

  - Installing symfony/browser-kit (2.3.x-dev v2.3.1)

  - Installing swiftmailer/swiftmailer (v5.0.1)

  - Installing predis/predis (0.8.x-dev 4576dc0)

  - Installing patchwork/utf8 (v1.1.8)

  - Installing nesbot/carbon (1.2.0)

  - Installing monolog/monolog (1.5.0)

  - Installing filp/whoops (1.0.6)

  - Installing ircmaxell/password-compat (1.0.x-dev v1.0.3)

  - Installing nikic/php-parser (dev-master 5ccf619)

  - Installing symfony/filesystem (dev-master 7975f9d)

  - Installing classpreloader/classpreloader (1.0.1)

  - Installing doctrine/dbal (dev-master 2.4.0-RC2)

  - Installing laravel/framework (4.0.x-dev 0c12b67)

  - Installing orchestra/testbench (2.0.x-dev v2.0.0)

symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/routing suggests installing symfony/config ()
symfony/routing suggests installing symfony/yaml ()
symfony/debug suggests installing symfony/class-loader ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
monolog/monolog suggests installing mlehner/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
```

### CODE REVIEW

**Comment by crynobone** [comment]
This should solve orchestral/testbench#4.

**Comment by schickling** [comment]
Wow. Thanks a lot. You also fixed the travis bug https://github.com/schickling/laravel-backup/issues/1 

So the problem was that the folders weren't in capital letters that travis failed? Strange that it worked in my local environment.

Anyway. Big thanks! :+1:

**Comment by crynobone** [comment]
Win/Mac are kinda forgiving when it come to case, Unix however aren't.

**Comment by schickling** [comment]
Good to know! Thanks for your support.

**Pull request merged**
